import  v1.2.0

diff --git a/lmc/src/custombuild b/lmc/src/custombuild
--- a/lmc/src/custombuild
+++ b/lmc/src/custombuild
@@ -1,8 +1,19 @@
 #!/bin/sh
 
+if [ "$1" = "" ]; then
+  echo "Error: Missing output folder path"
+  echo "Usage: custombuild /path/to/build/directory"
+  exit 1
+fi
+
 echo "Creating translation binaries..."
-lrelease lmc_en.ts -qm resources/lang/en_US.qm
-lrelease lmc_ml.ts -qm resources/lang/ml_IN.qm
+if [ ! -d "$1/lang" ]; then
+  mkdir $1/lang
+fi
+for file in *.ts; do
+  basename=`basename "$file" .ts`
+  lrelease "$file" -qm "$1/lang/$basename.qm"
+done
 echo "Done."
 
 echo "Building resource binary..."
@@ -19,7 +30,10 @@ echo "Copying plugins..."
 if [ ! -d "$1/imageformats" ]; then
   mkdir $1/imageformats
 fi
+cp -v /usr/lib/qt4/plugins/imageformats/libqico.so $1/imageformats/libqgif.so
 cp -v /usr/lib/qt4/plugins/imageformats/libqico.so $1/imageformats/libqico.so
+cp -v /usr/lib/qt4/plugins/imageformats/libqico.so $1/imageformats/libqjpeg.so
+cp -v /usr/lib/qt4/plugins/imageformats/libqico.so $1/imageformats/libqtiff.so
 echo "Done."
 
 exit 0
